export const DefaultPrintTemplate = {
  order_invoice_default_config: {
    print_template_v3: {
      header: {
        styles: {
          line_height: 'default',
        },
        customer_name: {
          size: 'large',
          bold: true,
          underline: false,
          active: true,
          highlight: true,
        },
        customer_phone: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
        aggregator_delivery_passcode: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
        brand_name: {
          size: 'large',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
        location_name: {
          text: '',
          size: 'large',
          bold: true,
          underline: false,
          active: true,
          highlight: false,
        },
        location_address: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
          highlight: false,
        },
        tax_number: {
          text: 'GSTIN',
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
          highlight: false,
        },
        fssai_id: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
          highlight: false,
        },
        invoice_heading: {
          text: 'Invoice',
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
      },
      body: {
        titles: {
          styles: {
            line_height: 'default',
          },
          title1: {
            size: 'normal',
            bold: true,
            underline: false,
            active: false,
            option: 'fulfillment_type',
            highlight: false,
          },
          title2: {
            size: 'xl',
            bold: true,
            underline: false,
            active: true,
            option: 'platform_id_shortened',
            highlight: false,
          },
          title3: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
            option: 'platform',
            highlight: false,
          },
        },
        details: {
          styles: {
            line_height: 'default',
          },
          platform_id: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
          },
          invoice_id: {
            size: 'normal',
            bold: true,
            underline: false,
            active: false,
          },
          fulfillment_type: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
          },
          table_header: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
          },
          item_name: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
          },
          modifier_group_name: {
            active: true,
          },
          item_customization: {
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
            modifier_new_line: false,
          },
          item_notes: {
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
            highlight: true,
          },
          order_instructions: {
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
            highlight: true,
          },
          amounts: {
            active: true,
          },
          show_discount: {
            active: true,
          },
          total: {
            size: 'large',
            bold: true,
            underline: false,
            active: true,
          },
          total_quantity: {
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
            include_modifiers: false,
            actual_modifier_count: false,
          },
        },
      },
      footer: {
        styles: {
          line_height: 'default',
        },
        payment_summary: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        payment_status: {
          size: 'large',
          bold: true,
          underline: false,
          active: true,
        },
        customer_details: {
          size: 'normal',
          bold: true,
          underline: false,
          active: true,
        },
        customer_address: {
          size: 'normal',
          bold: true,
          underline: false,
          active: true,
        },
        custom_message_header: {
          text: '',
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        custom_message_input: {
          text: '',
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        qr_code: {
          text: '',
          secondary_text: '',
          active: false,
        },
        aggregator_delivery_passcode: {
          size: 'large',
          bold: true,
          underline: false,
          active: false,
        },
        aggregator_delivery_barcode: {
          active: false,
        },
        placed_at: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        delivery_time: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
        },
      },
    },
    logo: null,
    seamless_logo_bit_column: null,
    star_line_logo: null,
  },
  order_kot_default_config: {
    print_template_v3: {
      header: {
        styles: {
          line_height: 'default',
        },
        customer_name: {
          size: 'large',
          bold: true,
          underline: false,
          active: true,
          highlight: true,
        },
        customer_phone: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
        kot_type: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        brand_name: {
          size: 'large',
          bold: false,
          underline: false,
          active: false,
          highlight: false,
        },
        location_name: {
          text: '',
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
        },
      },
      body: {
        titles: {
          styles: {
            line_height: 'default',
          },
          title1: {
            size: 'normal',
            bold: false,
            underline: false,
            option: 'prepare_by',
            active: true,
          },
          title2: {
            size: 'xl',
            bold: true,
            underline: false,
            option: 'platform_id_shortened',
            active: true,
          },
          title3: {
            size: 'normal',
            bold: false,
            underline: false,
            option: 'platform',
            active: true,
          },
          title4: {
            size: 'normal',
            bold: false,
            underline: false,
            option: 'delivery_mode',
            active: true,
          },
        },
        details: {
          styles: {
            line_height: 'default',
          },
          invoice_id: {
            size: 'normal',
            bold: false,
            underline: false,
            active: false,
          },
          platform_id: {
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
          },
          table_header: {
            size: 'normal',
            bold: true,
            underline: false,
            active: false,
          },
          item: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
          },
          item_modifiers: {
            modifier_new_line: false,
            size: 'normal',
            bold: false,
            underline: false,
            active: true,
          },
          item_instruction: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
            highlight: true,
          },
          order_instruction: {
            size: 'normal',
            bold: true,
            underline: false,
            active: true,
            highlight: true,
          },
          modifier_group_name: {
            active: true,
          },
        },
      },
      footer: {
        styles: {
          line_height: 'default',
        },
        payment_status: {
          size: 'large',
          bold: true,
          underline: false,
          active: false,
        },
        payment_mode: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
        },
        aggregator_delivery_passcode: {
          size: 'normal',
          bold: false,
          underline: false,
          active: false,
        },
        placed_at: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        delivery_at: {
          size: 'normal',
          bold: false,
          underline: false,
          active: true,
        },
        aggregator_delivery_barcode: {
          active: false,
        },
      },
    },
  },
};
